version: '2'
services:
    testmustapha-app:
        image: testmustapha
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://testmustapha-postgresql:5432/testMustapha
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    testmustapha-postgresql:
        extends:
            file: postgresql.yml
            service: testmustapha-postgresql
