version: '2'
services:
    testmustapha-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/testMustapha/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=testMustapha
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
